/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Raccoon;

import Raccoon.GuiDetalles;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Vanessa
 */
public class GuiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titúlo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        Feliz1 = new javax.swing.JLabel();
        Enojado2 = new javax.swing.JLabel();
        Travieso3 = new javax.swing.JLabel();
        Triste4 = new javax.swing.JLabel();
        Estresado5 = new javax.swing.JLabel();
        Coqueto6 = new javax.swing.JLabel();
        Cansado7 = new javax.swing.JLabel();
        Select1 = new javax.swing.JButton();
        Select11 = new javax.swing.JButton();
        Select2 = new javax.swing.JButton();
        Select22 = new javax.swing.JButton();
        Select3 = new javax.swing.JButton();
        Select23 = new javax.swing.JButton();
        Select4 = new javax.swing.JButton();
        Select24 = new javax.swing.JButton();
        Select5 = new javax.swing.JButton();
        Select25 = new javax.swing.JButton();
        Select6 = new javax.swing.JButton();
        Select26 = new javax.swing.JButton();
        Select7 = new javax.swing.JButton();
        Select27 = new javax.swing.JButton();
        Mapache = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titúlo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Titúlo.setText("En la escala de Raccoon ¿Cómo te sientes hoy?");
        getContentPane().add(Titúlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 630, 60));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        Logo.setText("jLabel1");
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 680, 100));

        Subtitulo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        Subtitulo.setText("Me siento...");
        getContentPane().add(Subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        Feliz1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Feliz1.setText("1.          Feliz");
        getContentPane().add(Feliz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 270, 30));

        Enojado2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Enojado2.setText("2.          Enojado");
        getContentPane().add(Enojado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 260, 30));

        Travieso3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Travieso3.setText("3.          Travieso");
        getContentPane().add(Travieso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 270, 30));

        Triste4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Triste4.setText("4.          Triste");
        getContentPane().add(Triste4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 270, 30));

        Estresado5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Estresado5.setText("5.          Estresado");
        getContentPane().add(Estresado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 270, 30));

        Coqueto6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Coqueto6.setText("6.          Coqueto");
        getContentPane().add(Coqueto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 270, 30));

        Cansado7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        Cansado7.setText("7.          Cansado");
        getContentPane().add(Cansado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 270, 30));

        Select1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select1.setText("Detalles");
        Select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select1ActionPerformed(evt);
            }
        });
        getContentPane().add(Select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 90, 30));

        Select11.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select11.setText("Elegir");
        Select11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select11ActionPerformed(evt);
            }
        });
        getContentPane().add(Select11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 70, 30));

        Select2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select2.setText("Detalles");
        Select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select2ActionPerformed(evt);
            }
        });
        getContentPane().add(Select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 90, 30));

        Select22.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select22.setText("Elegir");
        Select22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select22ActionPerformed(evt);
            }
        });
        getContentPane().add(Select22, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 70, 30));

        Select3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select3.setText("Detalles");
        Select3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select3ActionPerformed(evt);
            }
        });
        getContentPane().add(Select3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 90, 30));

        Select23.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select23.setText("Elegir");
        Select23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select23ActionPerformed(evt);
            }
        });
        getContentPane().add(Select23, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 70, 30));

        Select4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select4.setText("Detalles");
        Select4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select4ActionPerformed(evt);
            }
        });
        getContentPane().add(Select4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 90, 30));

        Select24.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select24.setText("Elegir");
        Select24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select24ActionPerformed(evt);
            }
        });
        getContentPane().add(Select24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 70, 30));

        Select5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select5.setText("Detalles");
        Select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select5ActionPerformed(evt);
            }
        });
        getContentPane().add(Select5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 90, 30));

        Select25.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select25.setText("Elegir");
        Select25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select25ActionPerformed(evt);
            }
        });
        getContentPane().add(Select25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 70, 30));

        Select6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select6.setText("Detalles");
        Select6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select6ActionPerformed(evt);
            }
        });
        getContentPane().add(Select6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 90, 30));

        Select26.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select26.setText("Elegir");
        Select26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select26ActionPerformed(evt);
            }
        });
        getContentPane().add(Select26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 70, 30));

        Select7.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select7.setText("Detalles");
        Select7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select7ActionPerformed(evt);
            }
        });
        getContentPane().add(Select7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 90, 30));

        Select27.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        Select27.setText("Elegir");
        Select27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select27ActionPerformed(evt);
            }
        });
        getContentPane().add(Select27, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 70, 30));

        Mapache.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Raccoon.jpg"))); // NOI18N
        Mapache.setText("jLabel1");
        getContentPane().add(Mapache, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 260));

        jButton1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, -1, -1));

        Fondo.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoo.png"))); // NOI18N
        Fondo.setText("jLabel2");
        Fondo.setMaximumSize(new java.awt.Dimension(550, 320));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select1ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Feliz.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Feliz");
    }//GEN-LAST:event_Select1ActionPerformed

    private void Select11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select11ActionPerformed
        JOptionPane.showMessageDialog(null, "Muy bien, eres un mapache feliz");
    }//GEN-LAST:event_Select11ActionPerformed

    private void Select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select2ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Enojado.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Enojado");
    }//GEN-LAST:event_Select2ActionPerformed

    private void Select22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select22ActionPerformed
        JOptionPane.showMessageDialog(null, "¡Cuidado con el mapache enojado!");
    }//GEN-LAST:event_Select22ActionPerformed

    private void Select23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select23ActionPerformed
       JOptionPane.showMessageDialog(null, "¡Travesuras!, que bien");
    }//GEN-LAST:event_Select23ActionPerformed

    private void Select3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select3ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Travieso.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Travieso");
    }//GEN-LAST:event_Select3ActionPerformed

    private void Select24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select24ActionPerformed
        JOptionPane.showMessageDialog(null, "Triste, que pena");
    }//GEN-LAST:event_Select24ActionPerformed

    private void Select4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select4ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Triste.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Triste");
    }//GEN-LAST:event_Select4ActionPerformed

    private void Select25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select25ActionPerformed
        JOptionPane.showMessageDialog(null, "¡Que estres, hace falta un día de descanso");
    }//GEN-LAST:event_Select25ActionPerformed

    private void Select5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select5ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Estresado.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Estresado");
    }//GEN-LAST:event_Select5ActionPerformed

    private void Select26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select26ActionPerformed
        JOptionPane.showMessageDialog(null, "¡Que lindura!");
    }//GEN-LAST:event_Select26ActionPerformed

    private void Select6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select6ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Coqueto.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Coqueto");
    }//GEN-LAST:event_Select6ActionPerformed

    private void Select27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select27ActionPerformed
        JOptionPane.showMessageDialog(null, "¡Que día más pesado!");
    }//GEN-LAST:event_Select27ActionPerformed

    private void Select7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select7ActionPerformed
        GuiDetalles y = new GuiDetalles();
        y.setVisible(true);
        ImageIcon val = new ImageIcon(getClass().getResource("/Imagenes/Cansado.jpg"));
        y.Imagen.setIcon(new ImageIcon(val.getImage()));
        y.Titulo.setText("Cansado");
    }//GEN-LAST:event_Select7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cansado7;
    private javax.swing.JLabel Coqueto6;
    private javax.swing.JLabel Enojado2;
    private javax.swing.JLabel Estresado5;
    private javax.swing.JLabel Feliz1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Mapache;
    private javax.swing.JButton Select1;
    private javax.swing.JButton Select11;
    private javax.swing.JButton Select2;
    private javax.swing.JButton Select22;
    private javax.swing.JButton Select23;
    private javax.swing.JButton Select24;
    private javax.swing.JButton Select25;
    private javax.swing.JButton Select26;
    private javax.swing.JButton Select27;
    private javax.swing.JButton Select3;
    private javax.swing.JButton Select4;
    private javax.swing.JButton Select5;
    private javax.swing.JButton Select6;
    private javax.swing.JButton Select7;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titúlo;
    private javax.swing.JLabel Travieso3;
    private javax.swing.JLabel Triste4;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
